---
- name: Create directory for Vim plug
  file:
    path: "{{ dev_tool.home_dir }}/.vim/autoload/"
    state: directory
    mode: 0740

- name: Download Vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ dev_tool.home_dir }}/.vim/autoload/plug.vim "

- name: Install oh_my_zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  ignore_errors: true

- name: Install zsh plugins
  git:
    repo: "https://github.com/zsh-users/{{ item }}.git"
    dest: "{{ dev_tool.home_dir }}/.oh-my-zsh/custom/plugins/{{ item }}"
    update: no
  with_items:
    - zsh-syntax-highlighting
    - zsh-completions

- name: Install Chrome Driver
  unarchive:
    src: "http://chromedriver.storage.googleapis.com/{{ chromedriver.version }}/chromedriver_mac64.zip"
    dest: "{{ dev_tool.home_dir }}/.local/bin/"
    remote_src: yes
    mode: 0750

- include: ./env.yml
- include: ./dotfile.yml
