---
- name: Install cask app
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - visual-studio-code
    - wireshark
    - 1password
    - virtualbox
    - vagrant
    - brave-browser
