---
- name: Install brew packages
  homebrew:
    name:
      - awscli
      - git
      - jq
      - openssl
      - tree
      - wget
      - zsh
      - go
      - packer
      - tmux
    state: present
