---
- name: Install cask app
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - wireshark
    - 1password
    - virtualbox
    - vagrant
    # https://github.com/ansible-collections/community.general/issues/1037 #
    #- visual-studio-code
    #- brave-browser
  ignore_errors: yes
